version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Elagin     
    ports:
      - '3306:3306' # my local port : container port
    volumes:
      - ./database/mysql-data:/var/lib/mysql # saving dump
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - database
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - frontend